// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbB4WE3r_y7kEhtY39a7C666G0RZfqsP8',
    appId: '1:825521162737:web:76a5a392e6b62f9c2a5c50',
    messagingSenderId: '825521162737',
    projectId: 'glifluttertask',
    authDomain: 'glifluttertask.firebaseapp.com',
    storageBucket: 'glifluttertask.appspot.com',
    measurementId: 'G-RGDYPL7YKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXh7_olN3Wm8LQ57J_zTCvDcaueD-TFtM',
    appId: '1:825521162737:android:40bc536c23f974172a5c50',
    messagingSenderId: '825521162737',
    projectId: 'glifluttertask',
    storageBucket: 'glifluttertask.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDilqCwsgLyJmQOQ1pbLwjJrTTgIG8-8p4',
    appId: '1:825521162737:ios:da73cf179a4c02f62a5c50',
    messagingSenderId: '825521162737',
    projectId: 'glifluttertask',
    storageBucket: 'glifluttertask.appspot.com',
    iosBundleId: 'com.example.glitask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDilqCwsgLyJmQOQ1pbLwjJrTTgIG8-8p4',
    appId: '1:825521162737:ios:da73cf179a4c02f62a5c50',
    messagingSenderId: '825521162737',
    projectId: 'glifluttertask',
    storageBucket: 'glifluttertask.appspot.com',
    iosBundleId: 'com.example.glitask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbB4WE3r_y7kEhtY39a7C666G0RZfqsP8',
    appId: '1:825521162737:web:d9701c46916568dc2a5c50',
    messagingSenderId: '825521162737',
    projectId: 'glifluttertask',
    authDomain: 'glifluttertask.firebaseapp.com',
    storageBucket: 'glifluttertask.appspot.com',
    measurementId: 'G-4NLT1T7ZGS',
  );
}
